import { lookName } from "./board-set";
import { SAMPLE_IMAGES } from "./media";
import { insightForIndex, richWhy } from "./rich-why.ts";
import type { RoutineId } from "./routines.ts";
import type { Climate, Extra, Garment, Look } from "./types";

const t = Date.now();

export const SAMPLE_TAGS: Record<string, string[]> = {
  g_navy_coat: ["Work", "Layering"],
  g_stone_jacket: ["School", "Weekend", "Travel"],
  g_camel_coat: ["Weekend", "Layering"],
  g_white_oxford: ["Work"],
  g_ivory_linen: ["School", "Weekend"],
  g_black_merino: ["Work", "Layering"],
  g_grey_tee: ["School", "Weekend", "Gym"],
  g_navy_knit: ["School", "Weekend"],
  g_charcoal_trouser: ["Work"],
  g_indigo_jean: ["School", "Weekend"],
  g_olive_chino: ["School", "Travel", "Weekend"],
  g_sand_short: ["School", "Weekend"],
  g_black_oxford: ["Work", "Wedding", "Black tie"],
  g_brown_chelsea: ["School", "Work", "Weekend"],
  g_white_sneaker: ["School", "Weekend", "Travel"],
  g_suede_loafer: ["School", "Weekend"],
  g_brown_belt: ["Work", "Weekend"],
  g_steel_watch: ["School", "Work", "Weekend"],
  g_navy_tie: ["Work", "Wedding"],
  g_black_tote: ["Work", "School"],
  g_canvas_weekender: ["Travel", "Weekend", "School"],
  g_navy_cap: ["School", "Weekend"],
  g_crew_pack: ["School", "Weekend", "Gym", "Travel"],
  g_denim_jacket: ["School", "Weekend"],
  g_rain_shell: ["School", "Weekend"],
  g_navy_harrington: ["School", "Weekend"],
  g_white_tee: ["School", "Weekend"],
  g_black_jean: ["School", "Weekend"],
  g_navy_quarter_zip: ["Gym"],
  g_black_hoodie: ["Gym", "Weekend"],
  g_gym_tee: ["Gym"],
  g_navy_perf_tee: ["Gym"],
  g_gym_jogger: ["Gym"],
  g_navy_jogger: ["Gym"],
  g_gym_trainer: ["Gym"],
  g_olive_gym_short: ["Gym"],
};

function sampleLook(
  garments: Garment[],
  spec: {
    id: string;
    garmentIds: string[];
    extraIds: string[];
    occasion: string;
    routine: RoutineId;
    climate: Climate;
    insight: number;
    createdAt: number;
  },
): Look {
  const pieces = spec.garmentIds
    .map((id) => garments.find((g) => g.id === id))
    .filter((g): g is Garment => Boolean(g));
  return {
    id: spec.id,
    name: lookName(pieces, spec.routine),
    garmentIds: spec.garmentIds,
    extraIds: spec.extraIds,
    occasion: spec.occasion,
    notes: richWhy(
      pieces,
      spec.routine,
      spec.climate,
      insightForIndex(spec.insight),
    ),
    source: "manual",
    createdAt: spec.createdAt,
  };
}

export function createSampleCloset(): {
  garments: Garment[];
  extras: Extra[];
  looks: Look[];
} {
  const garments: Garment[] = [
    {
      id: "g_navy_coat",
      name: "Navy wool overcoat",
      brand: "Arket",
      category: "outerwear",
      colorName: "Navy",
      hex: "#1c2a4a",
      material: "Wool",
      formality: "business",
      seasons: ["fall", "winter"],
      climate: ["cool", "cold"],
      notes: "Knee length. Quiet structure for the office walk.",
      tags: [],
      createdAt: t - 1,
    },
    {
      id: "g_stone_jacket",
      name: "Stone field jacket",
      brand: "Private White V.C.",
      category: "outerwear",
      colorName: "Stone",
      hex: "#a39e93",
      material: "Cotton",
      formality: "smart-casual",
      seasons: ["spring", "fall"],
      climate: ["mild", "cool", "rain"],
      notes: "Water-resistant. Weekend and travel layer.",
      tags: [],
      createdAt: t - 2,
    },
    {
      id: "g_camel_coat",
      name: "Camel polo coat",
      brand: "Uniqlo U",
      category: "outerwear",
      colorName: "Camel",
      hex: "#b08a5b",
      material: "Wool blend",
      formality: "smart-casual",
      seasons: ["fall", "winter"],
      climate: ["cool", "cold"],
      notes: "Warm, slightly oversized. Pairs with navy and grey.",
      tags: [],
      createdAt: t - 3,
    },
    {
      id: "g_white_oxford",
      name: "White oxford shirt",
      brand: "Asket",
      category: "tops",
      colorName: "White",
      hex: "#f7f7f4",
      material: "Cotton",
      formality: "business",
      seasons: ["all"],
      climate: ["warm", "mild", "cool"],
      notes: "Button-down. The default shirt.",
      tags: [],
      createdAt: t - 4,
    },
    {
      id: "g_ivory_linen",
      name: "Ivory linen shirt",
      brand: "Massimo Alba",
      category: "tops",
      colorName: "Ivory",
      hex: "#f3eee4",
      material: "Linen",
      formality: "casual",
      seasons: ["spring", "summer"],
      climate: ["hot", "warm"],
      notes: "Open collar. Wrinkles are the point.",
      tags: [],
      createdAt: t - 5,
    },
    {
      id: "g_black_merino",
      name: "Black merino crew",
      brand: "John Smedley",
      category: "tops",
      colorName: "Black",
      hex: "#1a1a1a",
      material: "Merino",
      formality: "smart-casual",
      seasons: ["fall", "winter"],
      climate: ["cool", "cold", "mild"],
      notes: "Fine gauge. Works under a coat or alone.",
      tags: [],
      createdAt: t - 6,
    },
    {
      id: "g_grey_tee",
      name: "Heather grey tee",
      brand: "Sunspel",
      category: "tops",
      colorName: "Grey",
      hex: "#8a8a8a",
      material: "Cotton",
      formality: "casual",
      seasons: ["all"],
      climate: ["hot", "warm", "mild"],
      notes: "Heavyweight. Weekend uniform.",
      tags: [],
      createdAt: t - 7,
    },
    {
      id: "g_navy_knit",
      name: "Navy polo knit",
      brand: "Anderson & Sheppard",
      category: "tops",
      colorName: "Navy",
      hex: "#1c2a4a",
      material: "Cotton knit",
      formality: "smart-casual",
      seasons: ["spring", "summer", "fall"],
      climate: ["warm", "mild", "cool"],
      notes: "Short sleeve. Dinner without a tie.",
      tags: [],
      createdAt: t - 8,
    },
    {
      id: "g_charcoal_trouser",
      name: "Charcoal wool trousers",
      brand: "Incotex",
      category: "bottoms",
      colorName: "Charcoal",
      hex: "#3a3a3c",
      material: "Wool",
      formality: "business",
      seasons: ["fall", "winter", "spring"],
      climate: ["mild", "cool", "cold"],
      notes: "Unpleated, tapered. Office and evening.",
      tags: [],
      createdAt: t - 9,
    },
    {
      id: "g_indigo_jean",
      name: "Dark indigo jeans",
      brand: "orSlow",
      category: "bottoms",
      colorName: "Indigo",
      hex: "#2c3a6a",
      material: "Denim",
      formality: "casual",
      seasons: ["all"],
      climate: ["warm", "mild", "cool"],
      notes: "Straight. No fading yet.",
      tags: [],
      createdAt: t - 10,
    },
    {
      id: "g_olive_chino",
      name: "Olive chinos",
      brand: "Drake's",
      category: "bottoms",
      colorName: "Olive",
      hex: "#5c6040",
      material: "Cotton twill",
      formality: "smart-casual",
      seasons: ["spring", "summer", "fall"],
      climate: ["warm", "mild", "cool"],
      notes: "Soft taper. Travel trousers.",
      tags: [],
      createdAt: t - 11,
    },
    {
      id: "g_sand_short",
      name: "Sand linen shorts",
      brand: "Howlin'",
      category: "bottoms",
      colorName: "Sand",
      hex: "#c4b49a",
      material: "Linen",
      formality: "casual",
      seasons: ["summer"],
      climate: ["hot", "warm"],
      notes: "Above the knee. Heatwave only.",
      tags: [],
      createdAt: t - 12,
    },
    {
      id: "g_black_oxford",
      name: "Black oxfords",
      brand: "Crockett & Jones",
      category: "footwear",
      colorName: "Black",
      hex: "#1a1a1a",
      material: "Calf leather",
      formality: "formal",
      seasons: ["all"],
      climate: ["mild", "cool", "cold"],
      notes: "Cap toe. Keep for ceremonies and boardrooms.",
      tags: [],
      createdAt: t - 13,
    },
    {
      id: "g_brown_chelsea",
      name: "Dark brown chelseas",
      brand: "Common Projects",
      category: "footwear",
      colorName: "Espresso",
      hex: "#3b2a22",
      material: "Leather",
      formality: "smart-casual",
      seasons: ["fall", "winter", "spring"],
      climate: ["mild", "cool", "cold", "rain"],
      notes: "Closed, weather-ready. The default shoe.",
      tags: [],
      createdAt: t - 14,
    },
    {
      id: "g_white_sneaker",
      name: "White leather sneakers",
      brand: "Koio",
      category: "footwear",
      colorName: "White",
      hex: "#f7f7f4",
      material: "Leather",
      formality: "casual",
      seasons: ["spring", "summer", "fall"],
      climate: ["hot", "warm", "mild"],
      notes: "Clean, no logos. Weekend and travel.",
      tags: [],
      createdAt: t - 15,
    },
    {
      id: "g_suede_loafer",
      name: "Taupe suede loafers",
      brand: "Baudoin & Lange",
      category: "footwear",
      colorName: "Sand",
      hex: "#c4b49a",
      material: "Suede",
      formality: "smart-casual",
      seasons: ["spring", "summer"],
      climate: ["warm", "mild"],
      notes: "Unlined. Not for rain.",
      tags: [],
      createdAt: t - 16,
    },
    {
      id: "g_brown_belt",
      name: "Brown leather belt",
      brand: "Anderson's",
      category: "accessories",
      colorName: "Oak",
      hex: "#6b4a2e",
      material: "Leather",
      formality: "smart-casual",
      seasons: ["all"],
      climate: ["hot", "warm", "mild", "cool", "cold"],
      notes: "Match to brown shoes.",
      tags: [],
      createdAt: t - 17,
    },
    {
      id: "g_steel_watch",
      name: "Steel field watch",
      brand: "Hamilton",
      category: "accessories",
      colorName: "Steel",
      hex: "#5c6b7a",
      material: "Steel",
      formality: "smart-casual",
      seasons: ["all"],
      climate: ["hot", "warm", "mild", "cool", "cold", "rain"],
      notes: "Everyday. Works with everything.",
      tags: [],
      createdAt: t - 18,
    },
    {
      id: "g_navy_tie",
      name: "Navy grenadine tie",
      brand: "Drake's",
      category: "accessories",
      colorName: "Navy",
      hex: "#1c2a4a",
      material: "Silk",
      formality: "business",
      seasons: ["all"],
      climate: ["mild", "cool", "cold"],
      notes: "Only with a collar.",
      tags: [],
      createdAt: t - 19,
    },
    {
      id: "g_black_tote",
      name: "Black leather tote",
      brand: "Mansur Gavriel",
      category: "bags",
      colorName: "Black",
      hex: "#1a1a1a",
      material: "Leather",
      formality: "business",
      seasons: ["all"],
      climate: ["mild", "cool", "cold", "rain"],
      notes: "Laptop and a book.",
      tags: [],
      createdAt: t - 20,
    },
    {
      id: "g_canvas_weekender",
      name: "Canvas weekender",
      brand: "Bennett Winch",
      category: "bags",
      colorName: "Khaki",
      hex: "#9a8f6e",
      material: "Canvas",
      formality: "casual",
      seasons: ["all"],
      climate: ["warm", "mild", "cool"],
      notes: "Overnight and flights.",
      tags: [],
      createdAt: t - 21,
    },
    {
      id: "g_navy_cap",
      name: "Navy baseball cap",
      brand: "J.Crew",
      category: "accessories",
      colorName: "Navy",
      hex: "#1c2a4a",
      material: "Cotton twill",
      formality: "casual",
      seasons: ["spring", "summer", "fall"],
      climate: ["hot", "warm", "mild", "cool"],
      notes: "Weekdays and weekends. Skip with a tie.",
      tags: [],
      createdAt: t - 22,
    },
    {
      id: "g_crew_pack",
      name: "New Crew backpack 30L",
      brand: "lululemon",
      category: "bags",
      colorName: "Black",
      hex: "#1a1a1a",
      material: "Nylon",
      formality: "casual",
      seasons: ["all"],
      climate: ["hot", "warm", "mild", "cool", "cold", "rain"],
      notes: "Laptop, water bottle, the whole day.",
      tags: [],
      createdAt: t - 23,
    },
    {
      id: "g_denim_jacket",
      name: "Indigo denim jacket",
      brand: "Levi's",
      category: "outerwear",
      colorName: "Indigo",
      hex: "#2c3a6a",
      material: "Denim",
      formality: "casual",
      seasons: ["spring", "fall"],
      climate: ["mild", "cool"],
      notes: "Campus layer. Not a blazer.",
      tags: [],
      createdAt: t - 24,
    },
    {
      id: "g_rain_shell",
      name: "Navy rain shell",
      brand: "Patagonia",
      category: "outerwear",
      colorName: "Navy",
      hex: "#1c2a4a",
      material: "Nylon",
      formality: "casual",
      seasons: ["all"],
      climate: ["rain", "cool", "mild"],
      notes: "Wet-weather layer, even on a mild day.",
      tags: [],
      createdAt: t - 25,
    },
    {
      id: "g_navy_harrington",
      name: "Navy harrington",
      brand: "Baracuta",
      category: "outerwear",
      colorName: "Navy",
      hex: "#1c2a4a",
      material: "Cotton",
      formality: "smart-casual",
      seasons: ["spring", "fall"],
      climate: ["cool", "mild", "cold"],
      notes: "Campus jacket, not a blazer.",
      tags: [],
      createdAt: t - 26,
    },
    {
      id: "g_white_tee",
      name: "White heavyweight tee",
      brand: "Uniqlo",
      category: "tops",
      colorName: "White",
      hex: "#f7f7f4",
      material: "Cotton",
      formality: "casual",
      seasons: ["all"],
      climate: ["hot", "warm", "mild", "cool"],
      notes: "The inside kit.",
      tags: [],
      createdAt: t - 27,
    },
    {
      id: "g_black_jean",
      name: "Black jeans",
      brand: "Uniqlo",
      category: "bottoms",
      colorName: "Black",
      hex: "#1a1a1a",
      material: "Denim",
      formality: "casual",
      seasons: ["all"],
      climate: ["cool", "cold", "mild"],
      notes: "School and weekend.",
      tags: [],
      createdAt: t - 28,
    },
    {
      id: "g_navy_quarter_zip",
      name: "Navy quarter-zip",
      brand: "lululemon",
      category: "tops",
      colorName: "Navy",
      hex: "#1c2a4a",
      material: "Fleece",
      formality: "athletic",
      seasons: ["fall", "winter", "spring"],
      climate: ["cool", "cold"],
      notes: "Lighter cold gym layer. It zips, it is not a jacket.",
      tags: [],
      createdAt: t - 29,
    },
    {
      id: "g_black_hoodie",
      name: "Black hoodie",
      brand: "Uniqlo U",
      category: "tops",
      colorName: "Black",
      hex: "#1a1a1a",
      material: "Fleece",
      formality: "athletic",
      seasons: ["fall", "winter", "spring"],
      climate: ["cool", "cold"],
      notes: "Cold gym layer — fleece, not a coat.",
      tags: [],
      createdAt: t - 30,
    },
    {
      id: "g_gym_tee",
      name: "Heather gym tee",
      brand: "lululemon",
      category: "tops",
      colorName: "Grey",
      hex: "#8a8a8a",
      material: "Polyester",
      formality: "athletic",
      seasons: ["all"],
      climate: ["hot", "warm", "mild", "cool"],
      notes: "On the floor. No extra layer in hot weather.",
      tags: [],
      createdAt: t - 31,
    },
    {
      id: "g_navy_perf_tee",
      name: "Navy performance tee",
      brand: "lululemon",
      category: "tops",
      colorName: "Navy",
      hex: "#1c2a4a",
      material: "Polyester",
      formality: "athletic",
      seasons: ["all"],
      climate: ["hot", "warm", "mild"],
      notes: "Gym only.",
      tags: [],
      createdAt: t - 32,
    },
    {
      id: "g_gym_jogger",
      name: "Charcoal gym joggers",
      brand: "lululemon",
      category: "bottoms",
      colorName: "Charcoal",
      hex: "#3a3a3c",
      material: "French terry",
      formality: "athletic",
      seasons: ["all"],
      climate: ["cool", "cold", "mild", "warm"],
      notes: "Move, then leave.",
      tags: [],
      createdAt: t - 33,
    },
    {
      id: "g_navy_jogger",
      name: "Navy joggers",
      brand: "lululemon",
      category: "bottoms",
      colorName: "Navy",
      hex: "#1c2a4a",
      material: "French terry",
      formality: "athletic",
      seasons: ["all"],
      climate: ["cool", "cold", "mild"],
      notes: "Gym bottoms.",
      tags: [],
      createdAt: t - 34,
    },
    {
      id: "g_gym_trainer",
      name: "White training sneakers",
      brand: "On",
      category: "footwear",
      colorName: "White",
      hex: "#f7f7f4",
      material: "Mesh",
      formality: "athletic",
      seasons: ["all"],
      climate: ["hot", "warm", "mild", "cool", "cold"],
      notes: "Gym floor.",
      tags: [],
      createdAt: t - 35,
    },
    {
      id: "g_olive_gym_short",
      name: "Olive gym shorts",
      brand: "lululemon",
      category: "bottoms",
      colorName: "Olive",
      hex: "#5c6040",
      material: "Nylon",
      formality: "athletic",
      seasons: ["spring", "summer"],
      climate: ["hot", "warm"],
      notes: "Hot gym only.",
      tags: [],
      createdAt: t - 36,
    },
  ];

  const extras: Extra[] = [
    {
      id: "e_cleanser",
      name: "Daily cleanser",
      brand: "Jack Black",
      kind: "skincare",
      notes: "First step, morning and night.",
      climate: ["hot", "warm", "mild", "cool", "cold"],
      formality: ["casual", "smart-casual", "business", "formal", "athletic"],
      tags: [],
      slot: "both",
      step: 1,
      createdAt: t - 30,
    },
    {
      id: "e_vitc",
      name: "Vitamin C serum",
      brand: "Jack Black",
      kind: "skincare",
      notes: "Morning only, under moisturizer.",
      climate: ["hot", "warm", "mild", "cool", "cold"],
      formality: ["casual", "smart-casual", "business", "formal"],
      tags: [],
      slot: "am",
      step: 2,
      createdAt: t - 31,
    },
    {
      id: "e_moist",
      name: "Oil-control moisturizer",
      brand: "Jack Black",
      kind: "skincare",
      notes: "After serums.",
      climate: ["hot", "warm", "mild", "cool", "cold"],
      formality: ["casual", "smart-casual", "business", "formal", "athletic"],
      tags: [],
      slot: "both",
      step: 3,
      createdAt: t - 32,
    },
    {
      id: "e_spf",
      name: "Face moisturizer SPF 20",
      brand: "Jack Black",
      kind: "skincare",
      notes: "Last morning step. Non-negotiable.",
      climate: ["hot", "warm", "mild", "cool"],
      formality: ["casual", "smart-casual", "business", "formal", "athletic"],
      tags: [],
      slot: "am",
      step: 4,
      createdAt: t - 33,
    },
    {
      id: "e_retinol",
      name: "Protein booster serum",
      brand: "Jack Black",
      kind: "skincare",
      notes: "Evening, after cleanser. Skip if skin is angry.",
      climate: ["mild", "cool", "cold"],
      formality: ["casual", "smart-casual", "business", "formal"],
      tags: [],
      slot: "pm",
      step: 2,
      createdAt: t - 34,
    },
    {
      id: "e_night",
      name: "Calming night cream",
      brand: "Jack Black",
      kind: "skincare",
      notes: "Seal the evening routine.",
      climate: ["cool", "cold", "mild"],
      formality: ["casual", "smart-casual", "business", "formal"],
      tags: [],
      slot: "pm",
      step: 3,
      createdAt: t - 35,
    },
    {
      id: "e_bergamot",
      name: "Colonia",
      brand: "Acqua di Parma",
      kind: "fragrance",
      notes: "Bright bergamot. Heat and linen.",
      climate: ["hot", "warm"],
      formality: ["casual", "smart-casual"],
      tags: ["Weekend"],
      family: "citrus",
      createdAt: t - 40,
    },
    {
      id: "e_vetiver",
      name: "Grey Flannel",
      brand: "Geoffrey Beene",
      kind: "fragrance",
      notes: "Dry woods. Office and autumn.",
      climate: ["mild", "cool"],
      formality: ["smart-casual", "business"],
      tags: ["Work"],
      family: "woody",
      createdAt: t - 41,
    },
    {
      id: "e_tonka",
      name: "Tonka",
      brand: "Reminiscence",
      kind: "fragrance",
      notes: "Evening weight. Coat weather.",
      climate: ["cool", "cold"],
      formality: ["business", "formal"],
      tags: ["Wedding"],
      family: "amber",
      createdAt: t - 42,
    },
    {
      id: "e_clay",
      name: "Claymation",
      brand: "Hanz de Fuko",
      kind: "grooming",
      notes: "Low shine, strong hold.",
      climate: ["hot", "warm", "mild", "cool", "cold"],
      formality: ["casual", "smart-casual", "business"],
      tags: [],
      createdAt: t - 50,
    },
    {
      id: "e_balm",
      name: "Santal 33",
      brand: "Le Labo",
      kind: "fragrance",
      notes: "Sandalwood. Cool evenings.",
      family: "woody",
      climate: ["mild", "cool", "cold"],
      formality: ["smart-casual", "business", "formal"],
      tags: [],
      createdAt: t - 51,
    },
  ];

  const looks: Look[] = [
    sampleLook(garments, {
      id: "l_school",
      garmentIds: [
        "g_stone_jacket",
        "g_grey_tee",
        "g_indigo_jean",
        "g_white_sneaker",
        "g_navy_cap",
        "g_crew_pack",
      ],
      extraIds: [],
      occasion: "School",
      routine: "school",
      climate: "cool",
      insight: 0,
      createdAt: t - 99,
    }),
    sampleLook(garments, {
      id: "l_school_knit",
      garmentIds: [
        "g_navy_knit",
        "g_olive_chino",
        "g_brown_chelsea",
        "g_steel_watch",
      ],
      extraIds: [],
      occasion: "School",
      routine: "school",
      climate: "mild",
      insight: 1,
      createdAt: t - 98,
    }),
    sampleLook(garments, {
      id: "l_school_linen",
      garmentIds: [
        "g_ivory_linen",
        "g_sand_short",
        "g_suede_loafer",
      ],
      extraIds: [],
      occasion: "School",
      routine: "school",
      climate: "hot",
      insight: 2,
      createdAt: t - 97,
    }),
    sampleLook(garments, {
      id: "l_monday",
      garmentIds: [
        "g_navy_coat",
        "g_white_oxford",
        "g_charcoal_trouser",
        "g_black_oxford",
        "g_steel_watch",
        "g_black_tote",
      ],
      extraIds: [],
      occasion: "Office",
      routine: "out",
      climate: "cool",
      insight: 0,
      createdAt: t - 100,
    }),
    sampleLook(garments, {
      id: "l_weekend",
      garmentIds: [
        "g_camel_coat",
        "g_ivory_linen",
        "g_olive_chino",
        "g_suede_loafer",
        "g_steel_watch",
      ],
      extraIds: [],
      occasion: "Weekend",
      routine: "weekend",
      climate: "mild",
      insight: 1,
      createdAt: t - 101,
    }),
  ];

  return {
    garments: garments.map((g) => ({
      ...g,
      imageSrc: SAMPLE_IMAGES[g.id],
      tags: SAMPLE_TAGS[g.id] ?? g.tags,
    })),
    extras: extras.map((e) => ({
      ...e,
      imageSrc: SAMPLE_IMAGES[e.id],
    })),
    looks,
  };
}
