/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClosetRouteImport } from './routes/closet'
import { Route as GroomingRouteImport } from './routes/grooming'
import { Route as LooksRouteImport } from './routes/looks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StylistRouteImport } from './routes/stylist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClosetRoute = ClosetRouteImport.update({
  id: '/closet',
  path: '/closet',
  getParentRoute: () => rootRouteImport,
} as any)
const GroomingRoute = GroomingRouteImport.update({
  id: '/grooming',
  path: '/grooming',
  getParentRoute: () => rootRouteImport,
} as any)
const LooksRoute = LooksRouteImport.update({
  id: '/looks',
  path: '/looks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StylistRoute = StylistRouteImport.update({
  id: '/stylist',
  path: '/stylist',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/closet': typeof ClosetRoute
  '/grooming': typeof GroomingRoute
  '/looks': typeof LooksRoute
  '/settings': typeof SettingsRoute
  '/stylist': typeof StylistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/closet': typeof ClosetRoute
  '/grooming': typeof GroomingRoute
  '/looks': typeof LooksRoute
  '/settings': typeof SettingsRoute
  '/stylist': typeof StylistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/closet': typeof ClosetRoute
  '/grooming': typeof GroomingRoute
  '/looks': typeof LooksRoute
  '/settings': typeof SettingsRoute
  '/stylist': typeof StylistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/closet' | '/grooming' | '/looks' | '/settings' | '/stylist'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/closet' | '/grooming' | '/looks' | '/settings' | '/stylist'
  id:
    | '__root__'
    | '/'
    | '/closet'
    | '/grooming'
    | '/looks'
    | '/settings'
    | '/stylist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClosetRoute: typeof ClosetRoute
  GroomingRoute: typeof GroomingRoute
  LooksRoute: typeof LooksRoute
  SettingsRoute: typeof SettingsRoute
  StylistRoute: typeof StylistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closet': {
      id: '/closet'
      path: '/closet'
      fullPath: '/closet'
      preLoaderRoute: typeof ClosetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grooming': {
      id: '/grooming'
      path: '/grooming'
      fullPath: '/grooming'
      preLoaderRoute: typeof GroomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/looks': {
      id: '/looks'
      path: '/looks'
      fullPath: '/looks'
      preLoaderRoute: typeof LooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stylist': {
      id: '/stylist'
      path: '/stylist'
      fullPath: '/stylist'
      preLoaderRoute: typeof StylistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClosetRoute: ClosetRoute,
  GroomingRoute: GroomingRoute,
  LooksRoute: LooksRoute,
  SettingsRoute: SettingsRoute,
  StylistRoute: StylistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
